function hideSidebar() {
    document.getElementById("sidebar").style.width="78px";
    document.getElementById("logo").style.display="none";
    document.getElementById("description").style.display="none";
    document.getElementById("avatar").style.display="none";
    document.getElementById("search-input").style.display="none";
    document.getElementById("search-input").removeAttribute("placeholder");
    document.getElementById("search-bar").style.width="50px";
    document.getElementById("menu-item1").style.display="none";
    document.getElementById("menu-item2").style.display="none";
    document.getElementById("menu-item3").style.display="none";
    document.getElementById("menu-item4").style.display="none";
    document.getElementById("menu-item5").style.display="none";
    document.getElementById("img1").style.marginLeft="93px";
    document.getElementById("img2").style.marginLeft="93px";
    document.getElementById("img3").style.marginLeft="93px";
    document.getElementById("img4").style.marginLeft="93px";
    document.getElementById("img5").style.marginLeft="93px";
}